##
# Autosign
autosign_grains_dir: /var/lib/foreman-proxy/salt/grains
autosign_file: /etc/salt/autosign.conf
# Uncomment the next line to make use of the autosign host name file (not recommended)
permissive_pki_access: True

##
# Node classifier
master_tops:
  ext_nodes: /usr/bin/foreman-node

##
# Pillar data access
ext_pillar:
  - puppet: /usr/bin/foreman-node

##
# Salt API access
external_auth:
  pam:
    saltuser:
      - '@runner'

rest_cherrypy:
  port: 9191
  host: 0.0.0.0
  ssl_key: /etc/foreman-proxy/foreman_ssl_key.pem
  ssl_crt: /etc/foreman-proxy/foreman_ssl_cert.pem

##
# Remote execution provider
publisher_acl:
  foreman-proxy:
    - state.template_str

##
# Reactors
reactor:
  - 'salt/auth': # Autosign reactor
    - /usr/share/foreman-proxy/salt/reactors/foreman_minion_auth.sls
  - 'salt/job/*/ret/*': # Report reactor
    - /usr/share/foreman-proxy/salt/reactors/foreman_report_upload.sls

file_roots:
  base:
    - /srv/salt

fileserver_backend:
  - git
#  - roots

gitfs_remotes:
   - https://github.com/mijuanlo/salttest.git
